#!/bin/bash

# Script'in yürütülebilir olmasını sağla
chmod +x "$0"

# 1. Gerekli Python paketlerini yükleme
echo "Gerekli Python paketlerini indiriyorum..."
pip install github3.py pyperclip tk
pip install pyautogui
pip install googletrans
pip install pynput

# 2. ~/github/MAIN dizinini oluşturma
echo "~/github/MAIN dizinini oluşturuyorum..."
mkdir -p ~/github/MAIN

# 3. Repo'yu indirme
echo "Repo'yu indiriyorum..."
git clone https://github.com/OmerFaruk-Celik/ceviri.git ~/github/MAIN/ceviri


# 5. Crontab'a komut ekleme

echo "Eski Crontab içeriklerini siliyorum."
crontab -l > crontab.txt
sed '/^\* \* \* \* \* \/usr\/bin\/python3 ~\/github\/MAIN\/ceviri\/ceviri.py > ~.*$/d' crontab.txt > new_crontab.txt
crontab new_crontab.txt

echo "Crontab'a komut ekliyorum..."
(crontab -l 2>/dev/null; echo "@reboot /usr/bin/python3 ~/github/MAIN/ceviri/ceviri.py > ~/github/MAIN/ceviri/output.log 2>&1") | crontab -

echo "INSTALL işlemi tamamlandı! reboot yaparak ceviri uygulamasını açıp kapatabilrisiniz alt+q tuşu sistemi aktif ya da pasif yapacaktır"

